using stackblob.Domain.Enums;
using stackblob.Infrastructure.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TimeZone = stackblob.Domain.Entities.Lookup.TimeZone;

namespace stackblob.Infrastructure.Persistence;

public static class StackblobDbContextSeed
{
    public static async Task SeedSampleData(StackblobDbContext context)
    {
        if (context.AttachmentTypes.Count() == 0)
        {
            context.AttachmentTypes.Add(new AttachmentTypeType { AttachmentTypeId = AttachmentType.QuestionAttachment, Name = "QuestionAttachment", Desc = "QuestionAttachment" });
            context.AttachmentTypes.Add(new AttachmentTypeType { AttachmentTypeId = AttachmentType.AnswerAttachment, Name = "AnswerAttachment", Desc = "AnswerAttachment" });
            context.AttachmentTypes.Add(new AttachmentTypeType { AttachmentTypeId = AttachmentType.ProfileBanner, Name = "ProfileBanner", Desc = "ProfileBanner" });
            context.AttachmentTypes.Add(new AttachmentTypeType { AttachmentTypeId = AttachmentType.ProfileAvatar, Name = "ProfileAvatar", Desc = "ProfileAvatar" });
        }

        if (context.RoleTypes.Count() == 0)
        {
            context.RoleTypes.Add(new RoleTypeType { RoleTypeId = RoleType.Developer, Name = "Developer", Desc = "Developer" });
            context.RoleTypes.Add(new RoleTypeType { RoleTypeId = RoleType.Student, Name = "Student", Desc = "Student" });
            context.RoleTypes.Add(new RoleTypeType { RoleTypeId = RoleType.Teacher, Name = "Teacher", Desc = "Teacher" });
            context.RoleTypes.Add(new RoleTypeType { RoleTypeId = RoleType.Hobby, Name = "Hobby", Desc = "Hobby" });
        }

        if (context.SocialTypes.Count() == 0) 
        { 
            context.SocialTypes.Add(new SocialTypeType { SocialTypeId = SocialType.Github, Name = "Github", Desc = "Github" });
            context.SocialTypes.Add(new SocialTypeType { SocialTypeId = SocialType.Twitter, Name = "Twitter", Desc = "Twitter" });
            context.SocialTypes.Add(new SocialTypeType { SocialTypeId = SocialType.LinkedIn, Name = "LinkedIn", Desc = "LinkedIn" });
            context.SocialTypes.Add(new SocialTypeType { SocialTypeId = SocialType.StackOverflow, Name = "StackOverflow", Desc = "StackOverflow" });
            context.SocialTypes.Add(new SocialTypeType { SocialTypeId = SocialType.Twitch, Name = "Twitch", Desc = "Twitch" });
        }

        if (context.TimeZones.Count() == 0)
        {
            context.TimeZones.AddRange(
                new TimeZone() { Description = "UTC", Offset = TimeSpan.FromHours(0) },
                new TimeZone() { Description = "CET", Offset = TimeSpan.FromHours(1) }
            );
        }

        if (context.Countries.Count() == 0)
        { 
            context.Countries.AddRange(
              new Country() { CountryName = "Afghanistan", Abbreviation = "AF" },
              new Country() { CountryName = "Ägypten", Abbreviation = "EG" },
              new Country() { CountryName = "Albanien", Abbreviation = "AL" },
              new Country() { CountryName = "Algerien", Abbreviation = "DZ" },
              new Country() { CountryName = "Amerikanisch Samoa", Abbreviation = "AS" },
              new Country() { CountryName = "Andorra", Abbreviation = "AD" },
              new Country() { CountryName = "Angola", Abbreviation = "AO" },
              new Country() { CountryName = "Anguilla", Abbreviation = "AI" },
              new Country() { CountryName = "Antarktis", Abbreviation = "AQ" },
              new Country() { CountryName = "Antigua und Barbuda", Abbreviation = "AG" },
              new Country() { CountryName = "Argentinien", Abbreviation = "AR" },
              new Country() { CountryName = "Armenien", Abbreviation = "AM" },
              new Country() { CountryName = "Aruba", Abbreviation = "AW" },
              new Country() { CountryName = "Ascensioninsel", Abbreviation = "SH" },
              new Country() { CountryName = "Aserbaidschan", Abbreviation = "AZ" },
              new Country() { CountryName = "Äthiopien", Abbreviation = "ET" },
              new Country() { CountryName = "Australien", Abbreviation = "AU" },
              new Country() { CountryName = "Bahamas", Abbreviation = "BS" },
              new Country() { CountryName = "Bahrain", Abbreviation = "BH" },
              new Country() { CountryName = "Bangladesh", Abbreviation = "BD" },
              new Country() { CountryName = "Barbados", Abbreviation = "BB" },
              new Country() { CountryName = "Belgien", Abbreviation = "BE" },
              new Country() { CountryName = "Belize", Abbreviation = "BZ" },
              new Country() { CountryName = "Benin", Abbreviation = "BJ" },
              new Country() { CountryName = "Bermuda", Abbreviation = "BM" },
              new Country() { CountryName = "Bhutan", Abbreviation = "BT" },
              new Country() { CountryName = "Bolivien", Abbreviation = "BO" },
              new Country() { CountryName = "Bosnien und Herzegowina", Abbreviation = "BA" },
              new Country() { CountryName = "Botswana", Abbreviation = "BW" },
              new Country() { CountryName = "Bouvet Insel", Abbreviation = "BV" },
              new Country() { CountryName = "Brasilien", Abbreviation = "BR" },
              new Country() { CountryName = "Britisches Territorium im indischen Ozean", Abbreviation = "IO" },
              new Country() { CountryName = "Brunei", Abbreviation = "BN" },
              new Country() { CountryName = "Bulgarien", Abbreviation = "BG" },
              new Country() { CountryName = "Burkina Faso", Abbreviation = "BF" },
              new Country() { CountryName = "Burma", Abbreviation = "MM" },
              new Country() { CountryName = "Burundi", Abbreviation = "BI" },
              new Country() { CountryName = "Chile", Abbreviation = "CL" },
              new Country() { CountryName = "China", Abbreviation = "CN" },
              new Country() { CountryName = "Cookinseln", Abbreviation = "CK" },
              new Country() { CountryName = "Costa Rica", Abbreviation = "CR" },
              new Country() { CountryName = "Dänemark", Abbreviation = "DK" },
              new Country() { CountryName = "Demokratische Volksrepublik Korea (Nord)", Abbreviation = "KP" },
              new Country() { CountryName = "Deutschland", Abbreviation = "DE" },
              new Country() { CountryName = "Dominica", Abbreviation = "DM" },
              new Country() { CountryName = "Dominikanische Republik", Abbreviation = "DO" },
              new Country() { CountryName = "Dschibuti", Abbreviation = "DJ" },
              new Country() { CountryName = "Ecuador", Abbreviation = "EC" },
              new Country() { CountryName = "Ecuatorialguinea", Abbreviation = "GQ" },
              new Country() { CountryName = "El Salvador", Abbreviation = "SV" },
              new Country() { CountryName = "Elfenbeinküste", Abbreviation = "CI" },
              new Country() { CountryName = "England", Abbreviation = "GB" },
              new Country() { CountryName = "Eritrea", Abbreviation = "ER" },
              new Country() { CountryName = "Estland", Abbreviation = "EE" },
              new Country() { CountryName = "Falklandinseln", Abbreviation = "FK" },
              new Country() { CountryName = "Faröer Inseln", Abbreviation = "FO" },
              new Country() { CountryName = "Fiji", Abbreviation = "FJ" },
              new Country() { CountryName = "Finnland", Abbreviation = "FI" },
              new Country() { CountryName = "Frankreich", Abbreviation = "FR" },
              new Country() { CountryName = "Französisch Guiana", Abbreviation = "GF" },
              new Country() { CountryName = "Französisch Polynesien", Abbreviation = "PF" },
              new Country() { CountryName = "Gabun", Abbreviation = "GA" },
              new Country() { CountryName = "Gambia", Abbreviation = "GM" },
              new Country() { CountryName = "Gazastreifen", Abbreviation = "PS" },
              new Country() { CountryName = "Georgien", Abbreviation = "GE" },
              new Country() { CountryName = "Ghana", Abbreviation = "GH" },
              new Country() { CountryName = "Gibraltar", Abbreviation = "GI" },
              new Country() { CountryName = "Grenada", Abbreviation = "GD" },
              new Country() { CountryName = "Griechenland", Abbreviation = "GR" },
              new Country() { CountryName = "Grönland", Abbreviation = "GL" },
              new Country() { CountryName = "Großbritannien", Abbreviation = "GB" },
              new Country() { CountryName = "Guadeloupe", Abbreviation = "GP" },
              new Country() { CountryName = "Guam", Abbreviation = "GU" },
              new Country() { CountryName = "Guatemala", Abbreviation = "GT" },
              new Country() { CountryName = "Guernsey", Abbreviation = "GG" },
              new Country() { CountryName = "Guinea", Abbreviation = "GN" },
              new Country() { CountryName = "Guinea-Bissau", Abbreviation = "GW" },
              new Country() { CountryName = "Guyana", Abbreviation = "GY" },
              new Country() { CountryName = "Haiti", Abbreviation = "HT" },
              new Country() { CountryName = "Honduras", Abbreviation = "HN" },
              new Country() { CountryName = "Hongkong", Abbreviation = "HK" },
              new Country() { CountryName = "Indien", Abbreviation = "IN" },
              new Country() { CountryName = "Indonesien", Abbreviation = "IDN" },
              new Country() { CountryName = "Irak", Abbreviation = "IQ" },
              new Country() { CountryName = "Iran", Abbreviation = "IR" },
              new Country() { CountryName = "Irland", Abbreviation = "IE" },
              new Country() { CountryName = "Island", Abbreviation = "IS" },
              new Country() { CountryName = "Isle of Man", Abbreviation = "IM" },
              new Country() { CountryName = "Israel", Abbreviation = "IL" },
              new Country() { CountryName = "Italien", Abbreviation = "IT" },
              new Country() { CountryName = "Jamaika", Abbreviation = "JM" },
              new Country() { CountryName = "Japan", Abbreviation = "JP" },
              new Country() { CountryName = "Jemen", Abbreviation = "YE" },
              new Country() { CountryName = "Jersey", Abbreviation = "JE" },
              new Country() { CountryName = "Johnstoninsel", Abbreviation = "JT" },
              new Country() { CountryName = "Jordan", Abbreviation = "JO" },
              new Country() { CountryName = "Jungfraueninseln, Amerikanisch", Abbreviation = "VI" },
              new Country() { CountryName = "Jungfraueninseln, Britisch", Abbreviation = "VG" },
              new Country() { CountryName = "Kaimaninseln", Abbreviation = "KY" },
              new Country() { CountryName = "Kambodscha", Abbreviation = "KH" },
              new Country() { CountryName = "Kamerun", Abbreviation = "CM" },
              new Country() { CountryName = "Kanada", Abbreviation = "CA" },
              new Country() { CountryName = "Kanalinseln", Abbreviation = "GB" },
              new Country() { CountryName = "Kap Verde", Abbreviation = "CV" },
              new Country() { CountryName = "Kasachstan", Abbreviation = "KZ" },
              new Country() { CountryName = "Katar", Abbreviation = "QA" },
              new Country() { CountryName = "Kenia", Abbreviation = "KE" },
              new Country() { CountryName = "Kirgistan", Abbreviation = "KG" },
              new Country() { CountryName = "Kiribati", Abbreviation = "KI" },
              new Country() { CountryName = "Kokosinseln", Abbreviation = "CC" },
              new Country() { CountryName = "Kolumbien", Abbreviation = "CO" },
              new Country() { CountryName = "Komoren", Abbreviation = "KM" },
              new Country() { CountryName = "Kongo, Demokratische Republik", Abbreviation = "CD" },
              new Country() { CountryName = "Kongo, Republik", Abbreviation = "CG" },
              new Country() { CountryName = "Kosovo", Abbreviation = "XK" },
              new Country() { CountryName = "Kroatien", Abbreviation = "HR" },
              new Country() { CountryName = "Kuba", Abbreviation = "CU" },
              new Country() { CountryName = "Kuwait", Abbreviation = "KW" },
              new Country() { CountryName = "Laos", Abbreviation = "LA" },
              new Country() { CountryName = "Lesotho", Abbreviation = "LS" },
              new Country() { CountryName = "Lettland", Abbreviation = "LV" },
              new Country() { CountryName = "Libanon", Abbreviation = "LB" },
              new Country() { CountryName = "Liberien", Abbreviation = "LR" },
              new Country() { CountryName = "Libyen", Abbreviation = "LY" },
              new Country() { CountryName = "Liechtenstein", Abbreviation = "LI" },
              new Country() { CountryName = "Litauen", Abbreviation = "LT" },
              new Country() { CountryName = "Luxemburg", Abbreviation = "LU" },
              new Country() { CountryName = "Macau", Abbreviation = "MO" },
              new Country() { CountryName = "Madagaskar", Abbreviation = "MG" },
              new Country() { CountryName = "Malawi", Abbreviation = "MW" },
              new Country() { CountryName = "Malaysien", Abbreviation = "MY" },
              new Country() { CountryName = "Malediven", Abbreviation = "MV" },
              new Country() { CountryName = "Mali", Abbreviation = "ML" },
              new Country() { CountryName = "Malta", Abbreviation = "MT" },
              new Country() { CountryName = "Marokko", Abbreviation = "MA" },
              new Country() { CountryName = "Marshallinseln", Abbreviation = "MH" },
              new Country() { CountryName = "Martinique", Abbreviation = "MQ" },
              new Country() { CountryName = "Mauretanien", Abbreviation = "MR" },
              new Country() { CountryName = "Mauritius", Abbreviation = "MU" },
              new Country() { CountryName = "Mayotte", Abbreviation = "YT" },
              new Country() { CountryName = "Mazedonien", Abbreviation = "MK" },
              new Country() { CountryName = "Mexiko", Abbreviation = "MX" },
              new Country() { CountryName = "Midwayinseln", Abbreviation = "MI" },
              new Country() { CountryName = "Mikronesien", Abbreviation = "FM" },
              new Country() { CountryName = "Moldawien", Abbreviation = "MD" },
              new Country() { CountryName = "Monaco", Abbreviation = "MC" },
              new Country() { CountryName = "Mongolei", Abbreviation = "MN" },
              new Country() { CountryName = "Montenegro", Abbreviation = "ME" },
              new Country() { CountryName = "Montserrat", Abbreviation = "MS" },
              new Country() { CountryName = "Mosambik", Abbreviation = "MZ" },
              new Country() { CountryName = "Namibia", Abbreviation = "NA" },
              new Country() { CountryName = "Nauru", Abbreviation = "NR" },
              new Country() { CountryName = "Nepal", Abbreviation = "NP" },
              new Country() { CountryName = "Neu-Kaledonien", Abbreviation = "NC" },
              new Country() { CountryName = "Neuseeland", Abbreviation = "NZ" },
              new Country() { CountryName = "Nicaragua", Abbreviation = "NI" },
              new Country() { CountryName = "Niederlande", Abbreviation = "NL" },
              new Country() { CountryName = "Niederländische Antillen", Abbreviation = "AN" },
              new Country() { CountryName = "Niger", Abbreviation = "NE" },
              new Country() { CountryName = "Nigeria", Abbreviation = "NG" },
              new Country() { CountryName = "Niue", Abbreviation = "NU" },
              new Country() { CountryName = "Nordirland", Abbreviation = "GB" },
              new Country() { CountryName = "Nördliche Marianainseln", Abbreviation = "MP" },
              new Country() { CountryName = "Norfolkinseln", Abbreviation = "NF" },
              new Country() { CountryName = "Norwegen", Abbreviation = "NO" },
              new Country() { CountryName = "Oman", Abbreviation = "OM" },
              new Country() { CountryName = "Österreich", Abbreviation = "AT" },
              new Country() { CountryName = "Osttimor", Abbreviation = "TP" },
              new Country() { CountryName = "Pakistan", Abbreviation = "PK" },
              new Country() { CountryName = "Palästina", Abbreviation = "PS" },
              new Country() { CountryName = "Palau", Abbreviation = "PW" },
              new Country() { CountryName = "Panama", Abbreviation = "PA" },
              new Country() { CountryName = "Papua Neuguinea", Abbreviation = "PG" },
              new Country() { CountryName = "Parguay", Abbreviation = "PY" },
              new Country() { CountryName = "Peru", Abbreviation = "PE" },
              new Country() { CountryName = "Philippinen", Abbreviation = "PH" },
              new Country() { CountryName = "Pitcairninseln", Abbreviation = "PN" },
              new Country() { CountryName = "Polen", Abbreviation = "PL" },
              new Country() { CountryName = "Portugal", Abbreviation = "PT" },
              new Country() { CountryName = "Puerto Rico", Abbreviation = "PR" },
              new Country() { CountryName = "Republik Korea", Abbreviation = "KR" },
              new Country() { CountryName = "Reunion", Abbreviation = "RE" },
              new Country() { CountryName = "Ruanda", Abbreviation = "RW" },
              new Country() { CountryName = "Rumänien", Abbreviation = "RO" },
              new Country() { CountryName = "Russland", Abbreviation = "RU" },
              new Country() { CountryName = "Salomoninseln", Abbreviation = "SB" },
              new Country() { CountryName = "Sambia", Abbreviation = "ZM" },
              new Country() { CountryName = "Samoa (West)", Abbreviation = "WS" },
              new Country() { CountryName = "San Marino", Abbreviation = "SM" },
              new Country() { CountryName = "Sankt Helena", Abbreviation = "SH" },
              new Country() { CountryName = "Sankt Kitts und Nevis", Abbreviation = "KN" },
              new Country() { CountryName = "Sankt Lucia", Abbreviation = "LC" },
              new Country() { CountryName = "Sankt Pierre und Miquelon", Abbreviation = "PM" },
              new Country() { CountryName = "Sankt Vincent und die Granadines", Abbreviation = "VC" },
              new Country() { CountryName = "Sao Tome und Principe", Abbreviation = "ST" },
              new Country() { CountryName = "Saudi Arabien", Abbreviation = "SA" },
              new Country() { CountryName = "Schottland", Abbreviation = "GB" },
              new Country() { CountryName = "Schweden", Abbreviation = "SE" },
              new Country() { CountryName = "Schweiz", Abbreviation = "CH" },
              new Country() { CountryName = "Senegal", Abbreviation = "SN" },
              new Country() { CountryName = "Serbien", Abbreviation = "RS" },
              new Country() { CountryName = "Seychellen", Abbreviation = "SC" },
              new Country() { CountryName = "Sierra Leone", Abbreviation = "SL" },
              new Country() { CountryName = "Simbabwe", Abbreviation = "ZW" },
              new Country() { CountryName = "Singapur", Abbreviation = "SG" },
              new Country() { CountryName = "Slowakei", Abbreviation = "SK" },
              new Country() { CountryName = "Slowenien", Abbreviation = "SI" },
              new Country() { CountryName = "Somalia", Abbreviation = "SO" },
              new Country() { CountryName = "Spanien", Abbreviation = "ES" },
              new Country() { CountryName = "Sri Lanka", Abbreviation = "LK" },
              new Country() { CountryName = "Südafrika", Abbreviation = "ZA" },
              new Country() { CountryName = "Sudan", Abbreviation = "SD" },
              new Country() { CountryName = "Suriname", Abbreviation = "SR" },
              new Country() { CountryName = "Swasiland", Abbreviation = "SZ" },
              new Country() { CountryName = "Syrien", Abbreviation = "SY" },
              new Country() { CountryName = "Taiwan", Abbreviation = "TW" },
              new Country() { CountryName = "Tansania", Abbreviation = "TZ" },
              new Country() { CountryName = "Tatschikistan", Abbreviation = "TJ" },
              new Country() { CountryName = "Thailand", Abbreviation = "TH" },
              new Country() { CountryName = "Togo", Abbreviation = "TG" },
              new Country() { CountryName = "Tokelau", Abbreviation = "TK" },
              new Country() { CountryName = "Tonga", Abbreviation = "TO" },
              new Country() { CountryName = "Trinidad und Tobago", Abbreviation = "TT" },
              new Country() { CountryName = "Tschad", Abbreviation = "TD" },
              new Country() { CountryName = "Tschechische Republik", Abbreviation = "CZ" },
              new Country() { CountryName = "Tunesien", Abbreviation = "TN" },
              new Country() { CountryName = "Türkei", Abbreviation = "TR" },
              new Country() { CountryName = "Turkmenistan", Abbreviation = "TM" },
              new Country() { CountryName = "Turks und Caicosinseln", Abbreviation = "TC" },
              new Country() { CountryName = "Tuvalu", Abbreviation = "TV" },
              new Country() { CountryName = "Uganda", Abbreviation = "UG" },
              new Country() { CountryName = "Ukraine", Abbreviation = "UA" },
              new Country() { CountryName = "Ungarn", Abbreviation = "HU" },
              new Country() { CountryName = "Uruguay", Abbreviation = "UY" },
              new Country() { CountryName = "Uzbekistan", Abbreviation = "UZ" },
              new Country() { CountryName = "Vanuatu", Abbreviation = "VU" },
              new Country() { CountryName = "Vatikan", Abbreviation = "VA" },
              new Country() { CountryName = "Venezuela", Abbreviation = "VE" },
              new Country() { CountryName = "Vereinigte Arabische Emirate", Abbreviation = "AE" },
              new Country() { CountryName = "Vereinigte Staaten von Amerika", Abbreviation = "US" },
              new Country() { CountryName = "Vereinigte Staaten, umliegende Inseln", Abbreviation = "UM" },
              new Country() { CountryName = "Vereinigtes Königreich", Abbreviation = "GB" },
              new Country() { CountryName = "Vietnam", Abbreviation = "VN" },
              new Country() { CountryName = "Wakeinsel", Abbreviation = "WK" },
              new Country() { CountryName = "Wallis und Futunainseln", Abbreviation = "WF" },
              new Country() { CountryName = "Weihnachtsinseln", Abbreviation = "CX" },
              new Country() { CountryName = "Weißrussland", Abbreviation = "BY" },
              new Country() { CountryName = "West Bank", Abbreviation = "PS" },
              new Country() { CountryName = "Westsahara", Abbreviation = "EH" },
              new Country() { CountryName = "Zentralafrikanische Republik", Abbreviation = "CF" },
              new Country() { CountryName = "Zypern", Abbreviation = "CY" }
            );
        }

        await context.SaveChangesAsync(default);

    }
}
